### ISSUE TITLE
Fix coding style

### ISSUE THREAD

**Issue by poying** [pcman-bbs/pcman.js#10]
https://github.com/pcman-bbs/pcman.js/tree/fix-coding-style
- [x] conn.js
- [x] inputhandler.js
- [x] pcman.js
- [x] termbuf.js
- [x] termsel.js
- [X] termview.js

**Comment by czchen** [comment]
@poying I plan to rewrite ansiparser.js, so you don't need to fix its coding style.

**Comment by poying** [comment]
@czchen OK. I've got it.

**Comment by czchen** [comment]
Merged in https://github.com/pcman-bbs/pcman.js/commit/a7a20d7343d1a973ce0c866055e2c8ebdce0eec8.
