### ISSUE TITLE
URI detection error

### ISSUE THREAD

**Issue by jessy1092** [pcman-bbs/pcman.js#14]
當畫面裡有 URI 時，會發生 Uncaught ReferenceError: col is not defined 。

![ps0544](https://cloud.githubusercontent.com/assets/4408071/9067208/b3968352-3b0e-11e5-8960-e5bd64718842.jpg)

**Comment by poying** [comment]
hmmm...
jshint 居然漏掉檢查變數宣告

**Comment by kidwm** [comment]
@jessy1092 看來你真的很喜歡音樂系女孩…
