### ISSUE TITLE
登入 PTT.cc 後進站統計次數畫面會一閃而過

### ISSUE THREAD

**Issue by kidwm** [pcman-bbs/pcman.js#17]
懷疑是 Enter 有時會重複送出
因為以 Enter 進入看板時，也會有看板畫面一閃而過的問題。

**Comment by jessy1092** [comment]
我昨天追到 實際上按下 Enter 只會送出一次 `'\r'`，然後就交給 conn.send 了，懷疑是編碼。
https://github.com/pcman-bbs/pcman.js/blob/master/lib/termview.js#L434-L436

**Comment by kidwm** [comment]
也有可能是 Buffer 沒清掉的問題？

**Comment by kidwm** [comment]
我現在這樣做只是 workaround ，希望之後整理程式碼時，有更好的處理。
